version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.groovy:groovy-all
    versions:
    - 3.0.7
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.apache.ant:ant
    versions:
    - 1.10.9
